### ISSUE TITLE
How to plot scatter plots?

### ISSUE THREAD

**Issue by pguso** [dbuezas/tslab-plotly#2]
Hi I tried to plot a scatter plot with sample code from the plotly.js site

```
import Plotly from "tslab-plotly";
import * as tslab from "tslab";

var trace1 = {
  x: [1, 2, 3, 4, 5],
  y: [1, 6, 3, 6, 1],
  mode: 'markers',
  type: 'scatter',
  name: 'Team A',
  text: ['A-1', 'A-2', 'A-3', 'A-4', 'A-5'],
  marker: { size: 12 }
};

var trace2 = {
  x: [1.5, 2.5, 3.5, 4.5, 5.5],
  y: [4, 1, 7, 1, 4],
  mode: 'markers',
  type: 'scatter',
  name: 'Team B',
  text: ['B-a', 'B-b', 'B-c', 'B-d', 'B-e'],
  marker: { size: 12 }
};

var data = [ trace1, trace2 ];

var layout = {
  xaxis: {
    range: [ 0.75, 5.25 ]
  },
  yaxis: {
    range: [0, 8]
  },
  title:'Data Labels Hover'
};

Plotly.newPlot(tslab, data, layout);
```

and get the following error, instead of a plot

> 36:23 - Argument of type '{ x: number[]; y: number[]; mode: string; type: string; name: string; text: string[]; marker: { size: number; }; }[]' is not assignable to parameter of type 'Data[]'.
> 36:23 - Type '{ x: number[]; y: number[]; mode: string; type: string; name: string; text: string[]; marker: { size: number; }; }' is not assignable to type 'Data'.
> 36:23 - Type '{ x: number[]; y: number[]; mode: string; type: string; name: string; text: string[]; marker: { size: number; }; }' is not assignable to type 'Partial<BoxPlotData>'.
> 36:23 - Types of property 'type' are incompatible.
> 36:23 - Type 'string' is not assignable to type '"box"'.

Am I missing something?

**Comment by dbuezas** [comment]
Thanks for the issue!

just add types to the traces:

```typescript
import Plotly from "tslab-plotly";
import * as tslab from "tslab";

var trace1: Plotly.Data = {
  x: [1, 2, 3, 4, 5],
  y: [1, 6, 3, 6, 1],
  mode: 'markers',
  type: 'scatter',
  name: 'Team A',
  text: ['A-1', 'A-2', 'A-3', 'A-4', 'A-5'],
  marker: { size: 12 }
};

var trace2: Plotly.Data = {
  x: [1.5, 2.5, 3.5, 4.5, 5.5],
  y: [4, 1, 7, 1, 4],
  mode: 'markers',
  type: 'scatter',
  name: 'Team B',
  text: ['B-a', 'B-b', 'B-c', 'B-d', 'B-e'],
  marker: { size: 12 }
};

var data = [ trace1, trace2 ] ;

var layout = {
  xaxis: {
    range: [ 0.75, 5.25 ]
  },
  yaxis: {
    range: [0, 8]
  },
  title:'Data Labels Hover'
};

Plotly.newPlot(tslab, data, layout);
```

**Comment by pguso** [comment]
Ah ok. Thanks for the quick response!

**Comment by pguso** [comment]
@dbuezas also I would like to say, thank you very much for providing this addon for tslab! I searched for finding a solution to use a jupyter like environment for typescript and have almost the same opportunity for handling data and visualize them. With your solution, I can use Plotly and that fits perfectly for me.
